### ISSUE TITLE
GaussianRasterizationSettings.new() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'

### ISSUE THREAD

**Issue by nateshi-0** [YanWenKun/Comfy3D-WinPortable#4]
everything installs and runs, but at the last moment when converting guassians to meshes, this error throws.

```
**[Comfy3D] Trellis Structured 3D Latents Models
GaussianRasterizationSettings.__new__() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'**
```

I looked at C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\renderers\gaussian_render.py

and see Original code use the Differential Gaussian Rasterization from https://github.com/autonomousvision/mip-splatting/tree/main/submodules/diff-gaussian-rasterization
    Modified to use the GaussianRasterizer from https://github.com/ashawkey/diff-gaussian-rasterization
    Only changes are the inputs to GaussianRasterizationSettings: kernel_size and subpixel_offset are commented out.

here is the report........

```
2024-12-28T23:15:59.284730 - got prompt
2024-12-28T23:15:59.847232 - [SPARSE][CONV] spconv algo: native2024-12-28T23:15:59.847232 - 
2024-12-28T23:16:00.932446 - [ATTENTION] Using backend: xformers2024-12-28T23:16:00.932446 - 
2024-12-28T23:16:26.724104 - Using cache found in C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\\TorchHome\hub\facebookresearch_dinov2_main
2024-12-28T23:16:26.795734 - Warn!: C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\\TorchHome\hub\facebookresearch_dinov2_main\dinov2\layers\swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")

2024-12-28T23:16:26.811663 - Warn!: C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\\TorchHome\hub\facebookresearch_dinov2_main\dinov2\layers\attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")

2024-12-28T23:16:26.840535 - Warn!: C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\\TorchHome\hub\facebookresearch_dinov2_main\dinov2\layers\block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")

2024-12-28T23:16:26.854473 - using MLP layer as FFN
2024-12-28T23:16:38.567541 - 
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  4.47it/s]2024-12-28T23:16:38.568483 - 
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.61it/s]2024-12-28T23:16:38.568483 - 
2024-12-28T23:16:43.962681 - 
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:05<00:00,  2.93it/s]2024-12-28T23:16:43.963677 - 
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:05<00:00,  2.32it/s]2024-12-28T23:16:43.963677 - 
2024-12-28T23:16:45.163664 - Before postprocess: 355540 vertices, 711224 faces2024-12-28T23:16:45.164079 - 
2024-12-28T23:16:50.989421 - 
Decimating Mesh: 100%|████████████████████████████████████████████████████████████████████████████████████[00:05<00:00]2024-12-28T23:16:50.989421 - 
Decimating Mesh: 100%|████████████████████████████████████████████████████████████████████████████████████[00:05<00:00]2024-12-28T23:16:50.989421 - 
2024-12-28T23:16:51.171670 - After decimate: 17677 vertices, 35560 faces2024-12-28T23:16:51.171670 - 
2024-12-28T23:16:55.883300 - 
Rasterizing:  96%|██████████████████████████████████████████████████████████████▏  | 956/1000 [00:02<00:00, 451.35it/s]2024-12-28T23:16:55.981917 - 
Rasterizing: 100%|████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 410.44it/s]2024-12-28T23:16:55.981917 - 
2024-12-28T23:16:56.079488 - Found 6963 invisible faces2024-12-28T23:16:56.079488 - 
2024-12-28T23:16:56.082473 - Dual graph: 53306 edges2024-12-28T23:16:56.082473 - 
2024-12-28T23:16:56.694776 - Mincut solved, start checking the cut2024-12-28T23:16:56.694776 - 
2024-12-28T23:16:56.859996 - Removed 9782 faces by mincut2024-12-28T23:16:56.859996 - 
2024-12-28T23:16:57.042192 - After remove invisible faces: 12980 vertices, 26105 faces2024-12-28T23:16:57.042192 - 
2024-12-28T23:16:59.756233 - 
Rendering: 0it [00:00, ?it/s]2024-12-28T23:16:59.827917 - 
Rendering: 0it [00:00, ?it/s]2024-12-28T23:16:59.827917 - 
2024-12-28T23:16:59.835882 - !!! Exception during processing !!! GaussianRasterizationSettings.__new__() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'
2024-12-28T23:16:59.873715 - Traceback (most recent call last):
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 3974, in run_model
    vertices, faces, uvs, texture = postprocessing_utils.finalize_mesh(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\utils\postprocessing_utils.py", line 451, in finalize_mesh
    observations, extrinsics, intrinsics = render_multiview(app_rep, resolution=1024, nviews=100)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\utils\render_utils.py", line 106, in render_multiview
    res = render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': (0, 0, 0)})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\utils\render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\renderers\gaussian_render.py", line 227, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_20241226_Trellis_special_win_portable\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\renderers\gaussian_render.py", line 77, in render
    raster_settings = GaussianRasterizationSettings(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GaussianRasterizationSettings.__new__() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'

2024-12-28T23:16:59.880684 - Prompt executed in 60.59 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":16,"nodes":[{"id":4,"type":"InvertMask","pos":[2206.3349609375,1107.0419921875],"size":[140,26],"flags":{},"order":2,"mode":0,"inputs":[{"name":"mask","type":"MASK","link":3,"label":"mask"}],"outputs":[{"name":"MASK","type":"MASK","links":[10],"slot_index":0,"label":"MASK"}],"properties":{"Node name for S&R":"InvertMask"},"widgets_values":[]},{"id":3,"type":"LoadImage","pos":[1838.76123046875,1029.599609375],"size":[353.18182373046875,489.7575378417969],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[11],"slot_index":0,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":[3],"slot_index":1,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["squirrel_girl_2.png","image"]},{"id":9,"type":"[Comfy3D] Load Trellis Structured 3D Latents Models","pos":[1846.1541748046875,909.7863159179688],"size":[344.3999938964844,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"trellis_pipe","type":"TRELLIS_PIPE","links":[9],"slot_index":0,"label":"trellis_pipe"}],"properties":{"Node name for S&R":"[Comfy3D] Load Trellis Structured 3D Latents Models"},"widgets_values":["JeffreyXiang/TRELLIS-image-large"]},{"id":12,"type":"[Comfy3D] Save 3D Mesh","pos":[2599.828125,789.9534912109375],"size":[315,58],"flags":{},"order":4,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":14,"label":"mesh"}],"outputs":[{"name":"save_path","type":"STRING","links":[15],"slot_index":0,"label":"save_path"}],"properties":{"Node name for S&R":"[Comfy3D] Save 3D Mesh"},"widgets_values":["Test_TRELLIS/mesh_0.glb"]},{"id":13,"type":"[Comfy3D] Preview 3DMesh","pos":[2895.747314453125,1004.837890625],"size":[600,500],"flags":{},"order":5,"mode":0,"inputs":[{"name":"mesh_file_path","type":"STRING","link":15,"widget":{"name":"mesh_file_path"},"label":"mesh_file_path"}],"outputs":[],"properties":{"Node name for S&R":"[Comfy3D] Preview 3DMesh"},"widgets_values":["",null]},{"id":10,"type":"[Comfy3D] Trellis Structured 3D Latents Models","pos":[2371.73876953125,1024.7462158203125],"size":[332.93328857421875,266],"flags":{},"order":3,"mode":0,"inputs":[{"name":"trellis_pipe","type":"TRELLIS_PIPE","link":9,"label":"trellis_pipe"},{"name":"reference_image","type":"IMAGE","link":11,"label":"reference_image"},{"name":"reference_mask","type":"MASK","link":10,"label":"reference_mask"}],"outputs":[{"name":"mesh","type":"MESH","links":[14],"slot_index":0,"label":"mesh"}],"properties":{"Node name for S&R":"[Comfy3D] Trellis Structured 3D Latents Models"},"widgets_values":[917472347346872,"randomize",7.5,12,3,12]}],"links":[[3,3,1,4,0,"MASK"],[9,9,0,10,0,"TRELLIS_PIPE"],[10,4,0,10,2,"MASK"],[11,3,0,10,1,"IMAGE"],[14,10,0,12,0,"MESH"],[15,12,0,13,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9646149645000031,"offset":[-1537.4692785410616,-527.1762283949823]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by nateshi-0** [comment]
for clarity, the above is for the Trellis specific portable.

**Comment by YanWenKun** [comment]
This is an confirmed issue that I'm going to fix in the next stable release.

I'm testing the new build and hopefully releasing it today or tomorrow.

For now you could run the `run_trellis_demo.bat` to run the TRELLIS gradio app.

**Comment by nateshi-0** [comment]
I've been running the gradio app and am really enjoying it.  It's the only way I've been able to get trellis running locally, despite trying every repo has it for comfy.  Thanks for making this available. Looking forward to the release to get it running in comfy as well.

**Comment by OnlyLAGcanSTOPme** [comment]
I ran the demo.bat but getting this error when I pressed the Generate button.

File "XXXXXXXX\Comfy3D_WinPortable_Trellis\Comfy3D_WinPortable\TRELLIS\trellis\renderers\gaussian_render.py", line 73, in render
    raster_settings = GaussianRasterizationSettings(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'

**Comment by YanWenKun** [comment]
@nateshi-0 @OnlyLAGcanSTOPme 
I just released a preview build, more documentation is on the way. You can try it now for TRELLIS workflow on ComfyUI:
https://github.com/YanWenKun/Comfy3D-WinPortable/releases/tag/r5-pt25

**Comment by nateshi-0** [comment]
> @nateshi-0 @OnlyLAGcanSTOPme I just released a preview build, more documentation is on the way. You can try it now for TRELLIS workflow on ComfyUI: https://github.com/YanWenKun/Comfy3D-WinPortable/releases/tag/r5-pt25

I was able to run it from inside comfyUI!!   thank you!
